/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';


const express = require('express');
const hostinfo = require('./hostInfo');

const app = express();

app.get('/api/userinfo', function (request, response) {
    let userInfo;
    hostinfo.getHostIp().then(ipAdress =>{

        userInfo = {
            "ipaddress": ipAdress,
            "language": request.headers["accept-language"].split(',')[0],
            "software": request.headers["user-agent"].split(' ')[1].replace('(','').replace(';','')
        };

      response.json(userInfo);
    });


});
app.listen(3000, function (err, data) {
    if (err) {
        throw err
    }
    console.log('Node.js listening on  3000 ... ');
});
module.exports = app;
